/*
 * Automatically generated by jrpcgen 1.0.7+ on 18/04/17 19:06
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.libvirt.types;
import org.dcache.xdr.*;
import java.io.IOException;

public class remote_network implements XdrAble, java.io.Serializable {

    public remote_nonnull_network value;

    private static final long serialVersionUID = 4753534018212085662L;

    public remote_network() {
    }

    public remote_network(remote_nonnull_network value) {
        this.value = value;
    }

    public remote_network(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        if ( value != null ) { xdr.xdrEncodeBoolean(true); value.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeBoolean() ? new remote_nonnull_network(xdr) : null;
    }

}
// End of remote_network.java
