/*
 * Automatically generated by jrpcgen 1.0.7+ on 18/04/17 19:06
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.libvirt;
import org.dcache.xdr.*;
import java.io.IOException;

public class remote_string implements XdrAble, java.io.Serializable {

    @Override
	public String toString() {
		return "remote_string [value=" + value + "]";
	}

	public remote_nonnull_string value;

    private static final long serialVersionUID = -4438614900157333607L;

    public remote_string() {
    }

    public remote_string(remote_nonnull_string value) {
        this.value = value;
    }

    public remote_string(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        if ( value != null ) { xdr.xdrEncodeBoolean(true); value.xdrEncode(xdr); } else { xdr.xdrEncodeBoolean(false); };
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeBoolean() ? new remote_nonnull_string(xdr) : null;
    }

}
// End of remote_string.java
