/*
 * Automatically generated by jrpcgen 1.0.7+ on 18/04/17 19:06
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.libvirt.types;
import org.dcache.xdr.*;
import java.io.IOException;

public class remote_nonnull_string implements XdrAble, java.io.Serializable {

    @Override
	public String toString() {
		return "remote_nonnull_string [value=" + value + "]";
	}

	public String value;

    private static final long serialVersionUID = 3961247821118954855L;

    public remote_nonnull_string() {
    }

    public remote_nonnull_string(String value) {
        this.value = value;
    }

    public remote_nonnull_string(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(value);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeString();
    }

}
// End of remote_nonnull_string.java
