/*
 * Automatically generated by jrpcgen 1.0.7+ on 18/04/17 19:06
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.libvirt.types;
import org.dcache.xdr.*;
import java.io.IOException;

public class remote_nonnull_network implements XdrAble, java.io.Serializable {
    protected remote_nonnull_string name;
    protected remote_uuid uuid;

    private static final long serialVersionUID = 5565965408306427365L;

    public void setName(remote_nonnull_string x) { this.name = x; }
    public remote_nonnull_string getName() { return this.name; }

    public void setUuid(remote_uuid x) { this.uuid = x; }
    public remote_uuid getUuid() { return this.uuid; }

    public remote_nonnull_network() {
    }

    public remote_nonnull_network(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        name.xdrEncode(xdr);
        uuid.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        name = new remote_nonnull_string(xdr);
        uuid = new remote_uuid(xdr);
    }

}
// End of remote_nonnull_network.java
