/*
 * Automatically generated by jrpcgen 1.0.7+ on 18/04/17 19:06
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 *
 * This version of jrpcgen adopted by dCache project
 * See http://www.dCache.ORG for details
 */
package org.libvirt.types;
import org.dcache.xdr.*;
import java.io.IOException;

public class remote_nonnull_domain implements XdrAble, java.io.Serializable {
    protected remote_nonnull_string name;
    protected remote_uuid uuid;
    protected int id;

    private static final long serialVersionUID = 4459830988281642149L;

    public void setName(remote_nonnull_string x) { this.name = x; }
    public remote_nonnull_string getName() { return this.name; }

    public void setUuid(remote_uuid x) { this.uuid = x; }
    public remote_uuid getUuid() { return this.uuid; }

    public void setId(int x) { this.id = x; }
    public int getId() { return this.id; }

    public remote_nonnull_domain() {
    }

    public remote_nonnull_domain(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        name.xdrEncode(xdr);
        uuid.xdrEncode(xdr);
        xdr.xdrEncodeInt(id);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        name = new remote_nonnull_string(xdr);
        uuid = new remote_uuid(xdr);
        id = xdr.xdrDecodeInt();
    }

}
// End of remote_nonnull_domain.java
